import "./styles/globals.css";
import {Vazirmatn} from "next/font/google";

const vazir = Vazirmatn({
  subsets: ['arabic'],
  weight:["400", "700"],
  variable:"--font-vazir"
})

export const metadata = {
  title: "اسفند🤍",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl" className={vazir.variable}>
      <body>{children}</body>
    </html>
  );
}
